#!/usr/bin/env bash
# display information about subdomains
subdomain=$1

if [ "$#" -eq 2 ]; then
    echo -n "The subdomain $2"
    dig "$2.$subdomain" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{print " is a " $4 " record and points to " $5}'
else
    dig "www.$subdomain" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{print "The subdomain www is a " $4 " record and points to " $5}'
    dig "lb-01.$subdomain" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{print "The subdomain lb-01 is a " $4 " record and points to " $5}'
    dig "web-01.$subdomain" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{print "The subdomain web-01 is a " $4 " record and points to " $5}'
    dig "web-02.$subdomain" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{print "The subdomain web-02 is a " $4 " record and points to " $5}'
fi