#!/usr/bin/env bash
# install nginx to create html file
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
