#!/usr/bin/env bash
# Install haproxy and config 2 server
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*

sudo echo -e "
frontend web_frontend
\tmode http
\tbind *:80
\tdefault_backend web_backend

backend web_backend
\tmode http
\tbalance roundrobin
\toption forwardfor
\thttp-request set-header X-Forwarded-Port %[dst_port]
\tserver web-01 35.190.138.21:80 check
\tserver web-02 3.94.64.65:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart