#!/usr/bin/env bash
# Install haproxy and config 2 server
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*

sudo echo -e "
frontend web_servers_frontend
\tmode http
\tbind *:80
\tdefault_backend web_servers_backend

backend web_servers_backend
\tbalance roundrobin
\toption forwardfor
\thttp-request set-header X-Forwarded-Port %[dst_port]
\tserver 1870-web-01 35.196.106.92:80 check
\tserver 1870-web-02 34.75.145.157:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
