#!/usr/bin/env bash
# displays numbers from 1 to 100; Fizzbuzz

for i in {1..100}
do
    if [ $(( i%15 )) -eq 0 ]
    then
        echo "Fizzbuzz"
    elif [ $(( i%3 )) -eq 0 ]
    then
        echo "Fizz"
    elif [ $(( i%5 )) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
done
