#!/usr/bin/env bash
# Display "Holberton School" 10 times and displays "Hi" for 9th iter

counter=1
while [ $counter -le 10 ]
do
    echo "Holberton School"
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    fi
    ((counter++))
done
