#!/usr/bin/env bash
# displays the time for 12 hours and 59 min
# Must use while loop (not allowed to use for and until)

m=0
while [ $m -le 12 ]
do
    echo "Hour: $m"
    min=1
    while [ $min -lt 60 ]
    do
        echo "$min"
        ((min++))
    done
    ((m++))
done
